<?php

declare(strict_types=1);

return [
    'packages' => [
        'blade-icons' => [
            '1.0' => [
                'navigation' => [
                    'main' => [
                        [
                            'name' => 'Installation',
                            'href' => '/packages/blade-icons/1.0/installation',
                        ],
                        [
                            'name' => 'GitHub',
                            'href' => 'https://github.com/faustbrian/blade-icons',
                            'external' => true,
                        ],
                    ],
                    'sidebar' => [
                        [
                            'title' => 'Getting Started',
                            'items' => [
                                ['name' => 'Installation', 'href' => '/packages/blade-icons/1.0/installation'],
                            ],
                        ],
                        [
                            'title' => 'Families',
                            'items' => [
                                ['name' => 'Academicons', 'href' => '/packages/blade-icons/1.0/families/academicons'],
                                ['name' => 'Akar Icons', 'href' => '/packages/blade-icons/1.0/families/akar-icons'],
                                ['name' => 'Anron', 'href' => '/packages/blade-icons/1.0/families/anron'],
                                ['name' => 'Ant Design Icons', 'href' => '/packages/blade-icons/1.0/families/ant-design-icons'],
                                ['name' => 'Bootstrap Icons', 'href' => '/packages/blade-icons/1.0/families/bootstrap-icons'],
                                ['name' => 'Boxicons', 'href' => '/packages/blade-icons/1.0/families/boxicons'],
                                ['name' => 'Bytesize Icons', 'href' => '/packages/blade-icons/1.0/families/bytesize-icons'],
                                ['name' => 'Carbon Icons', 'href' => '/packages/blade-icons/1.0/families/carbon-icons'],
                                ['name' => 'Clarity Icons', 'href' => '/packages/blade-icons/1.0/families/clarity-icons'],
                                ['name' => 'Codicons', 'href' => '/packages/blade-icons/1.0/families/codicons'],
                                ['name' => 'Coolicons', 'href' => '/packages/blade-icons/1.0/families/coolicons'],
                                ['name' => 'CoreUI Icons', 'href' => '/packages/blade-icons/1.0/families/coreui-icons'],
                                ['name' => 'Cryptocurrency Icons', 'href' => '/packages/blade-icons/1.0/families/cryptocurrency-icons'],
                                ['name' => 'CSS Icons', 'href' => '/packages/blade-icons/1.0/families/css-icons'],
                                ['name' => 'Devicons', 'href' => '/packages/blade-icons/1.0/families/devicons'],
                                ['name' => 'Elusive Icons', 'href' => '/packages/blade-icons/1.0/families/elusive-icons'],
                                ['name' => 'Emblemicons', 'href' => '/packages/blade-icons/1.0/families/emblemicons'],
                                ['name' => 'Entypo', 'href' => '/packages/blade-icons/1.0/families/entypo'],
                                ['name' => 'Eos Icons', 'href' => '/packages/blade-icons/1.0/families/eos-icons'],
                                ['name' => 'Eva Icons', 'href' => '/packages/blade-icons/1.0/families/eva-icons'],
                                ['name' => 'Evil Icons', 'href' => '/packages/blade-icons/1.0/families/evil-icons'],
                                ['name' => 'Feather Icons', 'href' => '/packages/blade-icons/1.0/families/feather-icons'],
                                ['name' => 'File Icons', 'href' => '/packages/blade-icons/1.0/families/file-icons'],
                                ['name' => 'Flag Icons', 'href' => '/packages/blade-icons/1.0/families/flag-icons'],
                                ['name' => 'Fluent UI System Icons', 'href' => '/packages/blade-icons/1.0/families/fluent-ui-system-icons'],
                                ['name' => 'Font Awesome', 'href' => '/packages/blade-icons/1.0/families/font-awesome'],
                                ['name' => 'Font Awesome Pro', 'href' => '/packages/blade-icons/1.0/families/font-awesome-pro'],
                                ['name' => 'Fontaudio', 'href' => '/packages/blade-icons/1.0/families/fontaudio'],
                                ['name' => 'Fontisto', 'href' => '/packages/blade-icons/1.0/families/fontisto'],
                                ['name' => 'Fork Awesome', 'href' => '/packages/blade-icons/1.0/families/fork-awesome'],
                                ['name' => 'Google Material Design Icons', 'href' => '/packages/blade-icons/1.0/families/google-material-design-icons'],
                                ['name' => 'Govicons', 'href' => '/packages/blade-icons/1.0/families/govicons'],
                                ['name' => 'Grommet Icons', 'href' => '/packages/blade-icons/1.0/families/grommet-icons'],
                                ['name' => 'Health Icons', 'href' => '/packages/blade-icons/1.0/families/health-icons'],
                                ['name' => 'Heroicons', 'href' => '/packages/blade-icons/1.0/families/heroicons'],
                                ['name' => 'Icomoon', 'href' => '/packages/blade-icons/1.0/families/icomoon'],
                                ['name' => 'Icomoon Essential', 'href' => '/packages/blade-icons/1.0/families/icomoon-essential'],
                                ['name' => 'Icomoon Ultimate', 'href' => '/packages/blade-icons/1.0/families/icomoon-ultimate'],
                                ['name' => 'Iconic', 'href' => '/packages/blade-icons/1.0/families/iconic'],
                                ['name' => 'Iconic Pro', 'href' => '/packages/blade-icons/1.0/families/iconic-pro'],
                                ['name' => 'Iconoir', 'href' => '/packages/blade-icons/1.0/families/iconoir'],
                                ['name' => 'Iconpark', 'href' => '/packages/blade-icons/1.0/families/iconpark'],
                                ['name' => 'Iconsax', 'href' => '/packages/blade-icons/1.0/families/iconsax'],
                                ['name' => 'Ikonate', 'href' => '/packages/blade-icons/1.0/families/ikonate'],
                                ['name' => 'Ionicons', 'href' => '/packages/blade-icons/1.0/families/ionicons'],
                                ['name' => 'Jam Icons', 'href' => '/packages/blade-icons/1.0/families/jam-icons'],
                                ['name' => 'Lindua', 'href' => '/packages/blade-icons/1.0/families/lindua'],
                                ['name' => 'Line Awesome', 'href' => '/packages/blade-icons/1.0/families/line-awesome'],
                                ['name' => 'Linearicons', 'href' => '/packages/blade-icons/1.0/families/linearicons'],
                                ['name' => 'Linearicons Premium', 'href' => '/packages/blade-icons/1.0/families/linearicons-premium'],
                                ['name' => 'Lucide', 'href' => '/packages/blade-icons/1.0/families/lucide'],
                                ['name' => 'Majesticons', 'href' => '/packages/blade-icons/1.0/families/majesticons'],
                                ['name' => 'Majesticons Pro', 'href' => '/packages/blade-icons/1.0/families/majesticons-pro'],
                                ['name' => 'Maki Icons', 'href' => '/packages/blade-icons/1.0/families/maki-icons'],
                                ['name' => 'Microns', 'href' => '/packages/blade-icons/1.0/families/microns'],
                                ['name' => 'Mono Icons', 'href' => '/packages/blade-icons/1.0/families/mono-icons'],
                                ['name' => 'Octicons', 'href' => '/packages/blade-icons/1.0/families/octicons'],
                                ['name' => 'Pepicons', 'href' => '/packages/blade-icons/1.0/families/pepicons'],
                                ['name' => 'Phosphor Flat Icons', 'href' => '/packages/blade-icons/1.0/families/phosphor-flat-icons'],
                                ['name' => 'Phosphor Icons', 'href' => '/packages/blade-icons/1.0/families/phosphor-icons'],
                                ['name' => 'Pixelarticons', 'href' => '/packages/blade-icons/1.0/families/pixelarticons'],
                                ['name' => 'Pixelarticons Pro', 'href' => '/packages/blade-icons/1.0/families/pixelarticons-pro'],
                                ['name' => 'Polaris Icons', 'href' => '/packages/blade-icons/1.0/families/polaris-icons'],
                                ['name' => 'Prime Icons', 'href' => '/packages/blade-icons/1.0/families/prime-icons'],
                                ['name' => 'Radix Icons', 'href' => '/packages/blade-icons/1.0/families/radix-icons'],
                                ['name' => 'Remix Icon', 'href' => '/packages/blade-icons/1.0/families/remix-icon'],
                                ['name' => 'Rpg Awesome', 'href' => '/packages/blade-icons/1.0/families/rpg-awesome'],
                                ['name' => 'Simple Icons', 'href' => '/packages/blade-icons/1.0/families/simple-icons'],
                                ['name' => 'Simple Line Icons', 'href' => '/packages/blade-icons/1.0/families/simple-line-icons'],
                                ['name' => 'System Uicons', 'href' => '/packages/blade-icons/1.0/families/system-uicons'],
                                ['name' => 'Tabler Icons', 'href' => '/packages/blade-icons/1.0/families/tabler-icons'],
                                ['name' => 'Teenyicons', 'href' => '/packages/blade-icons/1.0/families/teenyicons'],
                                ['name' => 'Twemoji', 'href' => '/packages/blade-icons/1.0/families/twemoji'],
                                ['name' => 'Typicons', 'href' => '/packages/blade-icons/1.0/families/typicons'],
                                ['name' => 'Uiw Icons', 'href' => '/packages/blade-icons/1.0/families/uiw-icons'],
                                ['name' => 'Unicons', 'href' => '/packages/blade-icons/1.0/families/unicons'],
                                ['name' => 'Vaadin Icons', 'href' => '/packages/blade-icons/1.0/families/vaadin-icons'],
                                ['name' => 'Weather Icons', 'href' => '/packages/blade-icons/1.0/families/weather-icons'],
                                ['name' => 'Yr Weather', 'href' => '/packages/blade-icons/1.0/families/yr-weather'],
                                ['name' => 'Zondicon', 'href' => '/packages/blade-icons/1.0/families/zondicon'],
                            ],
                        ],
                    ],
                ],
            ],
        ],
        'laravel-arch' => [
            '1.0' => [
                'navigation' => [
                    'main' => [
                        [
                            'name' => 'Installation',
                            'href' => '/packages/laravel-arch/1.0/installation',
                        ],
                        [
                            'name' => 'Configuration',
                            'href' => '/packages/laravel-arch/1.0/configuration',
                        ],
                        [
                            'name' => 'Annotations',
                            'href' => '/packages/laravel-arch/1.0/annotations/ranges',
                        ],
                        [
                            'name' => 'GitHub',
                            'href' => 'https://github.com/faustbrian/laravel-arch',
                            'external' => true,
                        ],
                    ],
                    'sidebar' => [
                        [
                            'title' => 'Getting Started',
                            'items' => [
                                ['name' => 'Installation', 'href' => '/packages/laravel-arch/1.0/installation'],
                                ['name' => 'Configuration', 'href' => '/packages/laravel-arch/1.0/configuration'],
                            ],
                        ],
                        [
                            'title' => 'Core Concepts',
                            'items' => [
                                ['name' => 'Environment', 'href' => '/packages/laravel-arch/1.0/core-concepts/environment'],
                                ['name' => 'Extension', 'href' => '/packages/laravel-arch/1.0/core-concepts/extension'],
                                ['name' => 'Generator', 'href' => '/packages/laravel-arch/1.0/core-concepts/generator'],
                                ['name' => 'Parser', 'href' => '/packages/laravel-arch/1.0/core-concepts/parser'],
                                ['name' => 'Renderer', 'href' => '/packages/laravel-arch/1.0/core-concepts/renderer'],
                                ['name' => 'Reporter', 'href' => '/packages/laravel-arch/1.0/core-concepts/reporter'],
                                ['name' => 'Statement', 'href' => '/packages/laravel-arch/1.0/core-concepts/statement'],
                                ['name' => 'Tokenizer', 'href' => '/packages/laravel-arch/1.0/core-concepts/tokenizer'],
                                ['name' => 'Tree', 'href' => '/packages/laravel-arch/1.0/core-concepts/tree'],
                            ],
                        ],
                        [
                            'title' => 'The Basics',
                            'items' => [
                                ['name' => 'Building Manifests', 'href' => '/packages/laravel-arch/1.0/the-basics/building-manifests'],
                                ['name' => 'Running Commands', 'href' => '/packages/laravel-arch/1.0/the-basics/running-commands'],
                            ],
                        ],
                        [
                            'title' => 'Digging Deeper',
                            'items' => [
                                ['name' => 'Creating an Extension', 'href' => '/packages/laravel-arch/1.0/digging-deeper/creating-an-extension'],
                            ],
                        ],
                        [
                            'title' => 'The Generators',
                            'items' => [
                                ['name' => 'Casts', 'href' => '/packages/laravel-arch/1.0/generators/casts'],
                                ['name' => 'Commands', 'href' => '/packages/laravel-arch/1.0/generators/commands'],
                                ['name' => 'Controllers', 'href' => '/packages/laravel-arch/1.0/generators/controllers'],
                                ['name' => 'Events', 'href' => '/packages/laravel-arch/1.0/generators/events'],
                                ['name' => 'Factories', 'href' => '/packages/laravel-arch/1.0/generators/factories'],
                                ['name' => 'Form Requests', 'href' => '/packages/laravel-arch/1.0/generators/form-requests'],
                                ['name' => 'Global Scopes', 'href' => '/packages/laravel-arch/1.0/generators/global-scopes'],
                                ['name' => 'Jobs', 'href' => '/packages/laravel-arch/1.0/generators/jobs'],
                                ['name' => 'Livewire', 'href' => '/packages/laravel-arch/1.0/generators/livewire'],
                                ['name' => 'Mails', 'href' => '/packages/laravel-arch/1.0/generators/mails'],
                                ['name' => 'Middleware', 'href' => '/packages/laravel-arch/1.0/generators/middleware'],
                                ['name' => 'Migrations', 'href' => '/packages/laravel-arch/1.0/generators/migrations'],
                                ['name' => 'Models', 'href' => '/packages/laravel-arch/1.0/generators/models'],
                                ['name' => 'Notifications', 'href' => '/packages/laravel-arch/1.0/generators/notifications'],
                                ['name' => 'Nova Actions', 'href' => '/packages/laravel-arch/1.0/generators/nova/actions'],
                                ['name' => 'Nova Dashboards', 'href' => '/packages/laravel-arch/1.0/generators/nova/dashboards'],
                                ['name' => 'Nova Filters', 'href' => '/packages/laravel-arch/1.0/generators/nova/filters'],
                                ['name' => 'Nova Lenses', 'href' => '/packages/laravel-arch/1.0/generators/nova/lenses'],
                                ['name' => 'Nova Metrics', 'href' => '/packages/laravel-arch/1.0/generators/nova/metrics'],
                                ['name' => 'Nova Resources', 'href' => '/packages/laravel-arch/1.0/generators/nova/resources'],
                                ['name' => 'Observers', 'href' => '/packages/laravel-arch/1.0/generators/observers'],
                                ['name' => 'Pivots', 'href' => '/packages/laravel-arch/1.0/generators/pivots'],
                                ['name' => 'Policies', 'href' => '/packages/laravel-arch/1.0/generators/policies'],
                                ['name' => 'Resources', 'href' => '/packages/laravel-arch/1.0/generators/resources'],
                                ['name' => 'Resource Collections', 'href' => '/packages/laravel-arch/1.0/generators/resource-collections'],
                                ['name' => 'Routes', 'href' => '/packages/laravel-arch/1.0/generators/routes'],
                                ['name' => 'Rules', 'href' => '/packages/laravel-arch/1.0/generators/rules'],
                                ['name' => 'Seeders', 'href' => '/packages/laravel-arch/1.0/generators/seeders'],
                                ['name' => 'Service Providers', 'href' => '/packages/laravel-arch/1.0/generators/service-providers'],
                                ['name' => 'Views', 'href' => '/packages/laravel-arch/1.0/generators/views'],
                                ['name' => 'View Components', 'href' => '/packages/laravel-arch/1.0/generators/view-components'],
                                ['name' => 'View Composers', 'href' => '/packages/laravel-arch/1.0/generators/view-composers'],
                            ],
                        ],
                        [
                            'title' => 'The Statements',
                            'items' => [
                                ['name' => 'Action Redirect', 'href' => '/packages/laravel-arch/1.0/statements/action-redirect'],
                                ['name' => 'Authorize', 'href' => '/packages/laravel-arch/1.0/statements/authorize'],
                                ['name' => 'Dispatch', 'href' => '/packages/laravel-arch/1.0/statements/dispatch'],
                                ['name' => 'Eloquent', 'href' => '/packages/laravel-arch/1.0/statements/eloquent'],
                                ['name' => 'Fire', 'href' => '/packages/laravel-arch/1.0/statements/fire'],
                                ['name' => 'Inertia Render', 'href' => '/packages/laravel-arch/1.0/statements/inertia/render'],
                                ['name' => 'Mail', 'href' => '/packages/laravel-arch/1.0/statements/mail'],
                                ['name' => 'Notification', 'href' => '/packages/laravel-arch/1.0/statements/notification'],
                                ['name' => 'Notify', 'href' => '/packages/laravel-arch/1.0/statements/notify'],
                                ['name' => 'Query', 'href' => '/packages/laravel-arch/1.0/statements/query'],
                                ['name' => 'Resource', 'href' => '/packages/laravel-arch/1.0/statements/resource'],
                                ['name' => 'Resource Collection', 'href' => '/packages/laravel-arch/1.0/statements/resource-collection'],
                                ['name' => 'Respond', 'href' => '/packages/laravel-arch/1.0/statements/respond'],
                                ['name' => 'Route Redirect', 'href' => '/packages/laravel-arch/1.0/statements/route-redirect'],
                                ['name' => 'Session', 'href' => '/packages/laravel-arch/1.0/statements/session'],
                                ['name' => 'Validate', 'href' => '/packages/laravel-arch/1.0/statements/validate'],
                                ['name' => 'View', 'href' => '/packages/laravel-arch/1.0/statements/view'],
                            ],
                        ],
                    ],
                ],
            ],
        ],
        'laravel-lighty' => [
            '1.0' => [
                'navigation' => [
                    'main' => [
                        [
                            'name' => 'Installation',
                            'href' => '/packages/laravel-lighty/1.0/installation',
                        ],
                        [
                            'name' => 'Configuration',
                            'href' => '/packages/laravel-lighty/1.0/configuration',
                        ],
                        [
                            'name' => 'Annotations',
                            'href' => '/packages/laravel-lighty/1.0/annotations/ranges',
                        ],
                        [
                            'name' => 'GitHub',
                            'href' => 'https://github.com/faustbrian/laravel-lighty',
                            'external' => true,
                        ],
                    ],
                    'sidebar' => [
                        [
                            'title' => 'Getting Started',
                            'items' => [
                                ['name' => 'Installation', 'href' => '/packages/laravel-lighty/1.0/installation'],
                                ['name' => 'Configuration', 'href' => '/packages/laravel-lighty/1.0/configuration'],
                            ],
                        ],
                        [
                            'title' => 'Annotations',
                            'items' => [
                                ['name' => 'Ranges', 'href' => '/packages/laravel-lighty/1.0/annotations/ranges'],
                                ['name' => 'Classes', 'href' => '/packages/laravel-lighty/1.0/annotations/classes'],
                                ['name' => 'Collapse', 'href' => '/packages/laravel-lighty/1.0/annotations/collapse'],
                                ['name' => 'Colorify', 'href' => '/packages/laravel-lighty/1.0/annotations/colorify'],
                                ['name' => 'Diffs', 'href' => '/packages/laravel-lighty/1.0/annotations/diffs'],
                                ['name' => 'Focus', 'href' => '/packages/laravel-lighty/1.0/annotations/focus'],
                                ['name' => 'Highlight', 'href' => '/packages/laravel-lighty/1.0/annotations/highlight'],
                                ['name' => 'Ids', 'href' => '/packages/laravel-lighty/1.0/annotations/ids'],
                                ['name' => 'Linkify', 'href' => '/packages/laravel-lighty/1.0/annotations/linkify'],
                                ['name' => 'Reindex', 'href' => '/packages/laravel-lighty/1.0/annotations/reindex'],
                            ],
                        ],
                        [
                            'title' => 'Extensions',
                            'items' => [
                                ['name' => 'CommonMark', 'href' => '/packages/laravel-lighty/1.0/extensions/commonmark'],
                            ],
                        ],
                        [
                            'title' => 'REST API',
                            'items' => [
                                ['name' => 'List Documents', 'href' => '/packages/laravel-lighty/1.0/rest-api#list-documents'],
                                ['name' => 'Create Document', 'href' => '/packages/laravel-lighty/1.0/rest-api#create-document'],
                                ['name' => 'Show Document', 'href' => '/packages/laravel-lighty/1.0/rest-api#show-document'],
                                ['name' => 'Delete Document', 'href' => '/packages/laravel-lighty/1.0/rest-api#delete-document'],
                                ['name' => 'List Languages', 'href' => '/packages/laravel-lighty/1.0/rest-api#list-languages'],
                                ['name' => 'Create Language', 'href' => '/packages/laravel-lighty/1.0/rest-api#create-language'],
                                ['name' => 'Show Language', 'href' => '/packages/laravel-lighty/1.0/rest-api#show-language'],
                                ['name' => 'Delete Language', 'href' => '/packages/laravel-lighty/1.0/rest-api#delete-language'],
                                ['name' => 'List Themes', 'href' => '/packages/laravel-lighty/1.0/rest-api#list-themes'],
                                ['name' => 'Create Theme', 'href' => '/packages/laravel-lighty/1.0/rest-api#create-theme'],
                                ['name' => 'Show Theme', 'href' => '/packages/laravel-lighty/1.0/rest-api#show-theme'],
                                ['name' => 'Delete Theme', 'href' => '/packages/laravel-lighty/1.0/rest-api#delete-theme'],
                            ],
                        ],
                    ],
                ],
            ],
        ],
        'laravel-json-rpc' => [
            '1.0' => [
                'navigation' => [
                    'main' => [
                        [
                            'name' => 'Installation',
                            'href' => '/packages/laravel-json-rpc/1.0/installation',
                        ],
                        [
                            'name' => 'Configuration',
                            'href' => '/packages/laravel-json-rpc/1.0/configuration',
                        ],
                    ],
                    'sidebar' => [
                        [
                            'title' => 'Getting Started',
                            'items' => [
                                ['name' => 'Installation', 'href' => '/packages/laravel-json-rpc/1.0/installation'],
                                ['name' => 'Configuration', 'href' => '/packages/laravel-json-rpc/1.0/configuration'],
                            ],
                        ],
                        [
                            'title' => 'The Basics',
                            'items' => [
                                ['name' => 'Servers', 'href' => '/packages/laravel-json-rpc/1.0/servers'],
                                ['name' => 'Procedures', 'href' => '/packages/laravel-json-rpc/1.0/procedures'],
                                ['name' => 'Requests', 'href' => '/packages/laravel-json-rpc/1.0/requests'],
                            ],
                        ],
                        [
                            'title' => 'Digging Deeper',
                            'items' => [
                                ['name' => 'Authentication', 'href' => '/packages/laravel-json-rpc/1.0/authentication'],
                                ['name' => 'Error Handling', 'href' => '/packages/laravel-json-rpc/1.0/error-handling'],
                                ['name' => 'Validation', 'href' => '/packages/laravel-json-rpc/1.0/validation'],
                            ],
                        ],
                    ],
                ],
            ],
        ],
    ],
];
